# TidyPy is a Python lint tool. https://pypi.org/project/tidypy/
# This file controls what checks to apply to our code.

[tool.tidypy]
# This file doesn't belong to us
exclude = [ "base58.py" ]

[tool.tidypy.pycodestyle]
disabled = [
    # E501 is 79-char max line length. GlacierScript has way too many
    # long lines to make this cleanup cost-effective. Maybe we revisit
    # this later when the rest is clean. See also line-too-long below.
    "E501",
]

[tool.tidypy.pydocstyle]
disabled = [
    # D212 and D213 have to do with multi-line docstrings: should they
    # start on the same line or next? I chose next line to be
    # consistent with what most of GlacierScript uses.
    "D212",
]

[tool.tidypy.pylint]
disabled = [
    # 100-char max line length. GlacierScript has way too many long
    # lines to make this cleanup cost-effective. Maybe we revisit this
    # later when the rest is clean. See also E501 above.
    "line-too-long",
]


[tool.tidypy.secrets]
disabled = [
    # We have lots of high-entropy strings. They are not secrets.
    "HexHighEntropyString",
    "Base64HighEntropyString",
]
