#!/bin/bash

if [[ -z $1 ]]; then

    echo "Usage: t/convert-test-to-regtest <name>"
    echo ""
    echo "This will convert <name>.run from testnet to regtest, recreate its"
    echo "golden file to match, and git commit the change."
    echo ""
    echo "Run this from the git root, i.e. same directory as glacierscript.py."
    echo ""
    echo "This assumes a clean, successful withdrawal transaction. If the test"
    echo "is covering error conditions, etc., you might need to convert by hand."
    exit 1
fi


set -e

mkdir -p testrun/online
(cd testrun/online && ../../t/online_regtest_wallet.py convert-testnet-to-regtest ../../t/$1.run)

make t/$1.test || /bin/true

killall bitcoind

if [[ -e t/$1.out ]]; then
    cp t/$1.{out,golden}
fi

make t/$1.test

make clean

git commit -am "Convert $1 to regtest"
