#!/bin/bash

if [[ -z $1 ]]; then

    echo "Usage: t/recreate-as-psbt <name>"
    echo ""
    echo "This will recreate create-withdrawal-data.<name>.run into a PSBT test,"
    echo "make a golden file to match, and git commit the change."
    echo ""
    echo "Run this from the git root, i.e. same directory as glacierscript.py."
    echo ""
    echo "This assumes a clean, successful withdrawal transaction. If the test"
    echo "is covering error conditions, etc., you might need to convert by hand."
    exit 1
fi


set -e

mkdir -p testrun/online
(cd testrun/online && ../../t/online_regtest_wallet.py recreate-as-psbt ../../t/create-withdrawal-data.$1.run)

make t/sign-psbt.$1.test || /bin/true

killall bitcoind

if [[ -e t/sign-psbt.$1.out ]]; then
    cp t/sign-psbt.$1.{out,golden}
fi

make t/sign-psbt.$1.test

make clean

git add t/sign-psbt.$1.*
git commit -am "Recreate create-withdrawal-data.$1 as sign-psbt"
