Are you running this on a computer WITHOUT a network connection of any kind? (y/n)?Have the wireless cards in this computer been physically removed? (y/n)?Are you running on battery power? (y/n)?Are you running on an operating system booted from a USB drive? (y/n)?Is your screen hidden from view of windows, cameras, and other people? (y/n)?Are smartphones and all other nearby devices turned off and in a Faraday bag? (y/n)?Input a filename located in the current directory which contains the PSBT:
Output from subprocess: error code: -22
error message:
TX decode failed Outputs provided does not match the number of outputs in transaction.: iostream error

Traceback (most recent call last):
  File "../../glacierscript.py", line <.*> in checkoutput
    raise subprocess.CalledProcessError(retcode, cmd_list, output=output)
subprocess.CalledProcessError: Command '['bitcoin-cli', '-testnet', '-rpcport=<\d+>', '-datadir=../bitcoin-data/<\d+>', 'decodepsbt', 'cHNidP8BAM4CAAAABFAqXQa2PFg8pAnCVBZEiWjWiT9kCtvhtFL789qp9txJAQAAAAD/////FIiqv5nPcATIXvaPyvXKTHdvvZ4Lx/hcq7eB5JCMoWsAAAAAAP////+WskoLtxYV1tlohvYVa1+LaDA7VJVXOImftYpHs/WL4AAAAAAA/////xhRnXo1X5jbt57UFzdk97EVrsku74Mt6pqpdizQEcG/AAAAAAD/////AeH1IQoAAAAAF6kUhUbnR8gJQ3awoK9EvFu7jdTwIY2HAAAAAAABAIoCAAAAAcC/NJJsUqFeod2Avd7/ssZzjybwFIYqGmEvQmuHYyPVAQAAABcWABTQB03a+UQVNYAF1jYLqSn2KKi6wf////8CEH6IAgAAAAAXqRSp4cLcMuRItnG9EaM4hGn3pIcmX4egf4gCAAAAABepFL05lruabEAdp+ZdTbs6m5eM0EXshwAAAAABBItSIQPRTdz7aBf1V5aVu7PrPhhYh78pQrAx5vcWNDuP5+no4iECj81G+GFLLL8xgJaWgkKh4ivPttjyttyTnIwnw0eyk3shAxWstVASD0zctGDVxJCAq1CMpMzY3t7Kwi/urIzQF9TBIQIrBj7i8i+eGYLBQP53hnLGgxEaeW3Mzb1Hu2Xj1gipg1SuAAEAcgIAAAAB2T89qSgOt9YXHadGJn70ael9dGX3nqRqReB0ld/Cd1MBAAAAAP////8CCEuHAgAAAAAXqRS9OZa7mmxAHafmXU27OpuXjNBF7Idws4kCAAAAABYAFEdvx77Y6Nd+j/cMVGveWto3zc7GAAAAAAEEi1IhA9FN3PtoF/VXlpW7s+s+GFiHvylCsDHm9xY0O4/n6ejiIQKPzUb4YUssvzGAlpaCQqHiK8+22PK23JOcjCfDR7KTeyEDFay1UBIPTNy0YNXEkICrUIykzNje3srCL+6sjNAX1MEhAisGPuLyL54ZgsFA/neGcsaDERp5bczNvUe7ZePWCKmDVK4AAQBqAgAAAAFtxht/2X8gayzOn51bht9UhI9RgjHNFt6KzM1CxtZ3yAEAAAAXFgAUrhC9pL7tuNF0nizVDDiqX/yG5hP/////AYh9iAIAAAAAF6kUvTmWu5psQB2n5l1Nuzqbl4zQReyHAAAAAAEEi1IhA9FN3PtoF/VXlpW7s+s+GFiHvylCsDHm9xY0O4/n6ejiIQKPzUb4YUssvzGAlpaCQqHiK8+22PK23JOcjCfDR7KTeyEDFay1UBIPTNy0YNXEkICrUIykzNje3srCL+6sjNAX1MEhAisGPuLyL54ZgsFA/neGcsaDERp5bczNvUe7ZePWCKmDVK4AAA==']' returned non-zero exit status 22<\.?>
